### PR TITLE
fix(tests): Fix first_function unit test

### PR DESCRIPTION
**Pull request by Nr18**
*Issue #, if available:*
N/A

*Description of changes:*
If the project is deployed without API Gateway support the test will fail fixed that by adding the "same" if statement to the test to change the assertion if needed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Nice catch! What about separating them completely?

* If user doesn't want to use API GW the fixture (e.g. payload) will also be lean

That would need another fixture and add conditionals around so depending on the selection option it becomes clean enough otherwise we are injecting all that data that the Lambda itself will not use it

**Comment by Nr18** [comment]
Yes the fixture is not needed at all when you deploy it without the API Gateway.

**Comment by h1f1x** [comment]
+1 like this. And missed this.
One question:
```
return { "test": "body" }
```
Could we do this vice-versa, it confuses me a bit. Or make it more obvious, that the content here is not relevant.
Alternative A:
```
return { "body": "test" }
```
Alternative B:
```
return { "foo": "bar" }
```

**Comment by Nr18** [comment]
@h1f1x nice catch didn't see that one i went with B due to the fact that it's a lambda event so A with `body` might still confuse people.

**Comment by h1f1x** [comment]
@heitorlessa feel free to merge :)

**Comment by h1f1x** [comment]
@Nr18 I have found a small glitch.
In first_function/app.py the lambda_handler() refers to api_gw! Can you fix this? Sorry, I could not edit or contribute to your PR by myself ;)

**Comment by heitorlessa** [comment]
For some reason my Inbox keeps marking github updates as Spam ;(

I’ll look into this early next week, apologies for the delay on that

**Comment by Nr18** [comment]
@h1f1x not sure what you mean... Can you point out what you want to have changed or do it your self i added you as a collaborator?

**Comment by h1f1x** [comment]
@Nr18 : done, thanks for open the fork ;) And sorry for the delay on my side ;)
@heitorlessa: now again, ready for merge.

**Comment by heitorlessa** [comment]
Thanks again for all help :)

**Comment by Nr18** [comment]
@h1f1x no problem needed to see the commit didn’t realize that you ment the comment ;-)

@heitorlessa your welcome

**Pull request merged**
